# Generated by Django 5.0.4 on 2026-05-27 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmissionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.IntegerField(
                        choices=[(1, "Scope 1"), (2, "Scope 2"), (3, "Scope 3")]
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fuel_diesel", "Diesel"),
                            ("fuel_petrol", "Petrol / Gasoline"),
                            ("fuel_natural_gas", "Natural Gas"),
                            ("electricity", "Electricity"),
                            ("flight", "Flight"),
                            ("hotel", "Hotel"),
                            ("car_rental", "Car Rental"),
                            ("taxi", "Taxi / Rideshare"),
                            ("train", "Train"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "activity_value_raw",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "activity_unit_raw",
                    models.CharField(
                        help_text="Original unit string from source", max_length=30
                    ),
                ),
                (
                    "activity_value_norm",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Value in canonical unit (litres / kWh / km / room-nights)",
                        max_digits=18,
                    ),
                ),
                ("activity_unit_norm", models.CharField(max_length=20)),
                (
                    "co2e_kg",
                    models.DecimalField(
                        decimal_places=4, help_text="kg CO2e", max_digits=18
                    ),
                ),
                (
                    "emission_factor",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Factor applied (kgCO2e per unit)",
                        max_digits=12,
                    ),
                ),
                (
                    "factor_version",
                    models.CharField(default="DEFRA-2023", max_length=20),
                ),
                (
                    "activity_date",
                    models.DateField(
                        help_text="Date of the activity (not upload date)"
                    ),
                ),
                (
                    "activity_period_end",
                    models.DateField(
                        blank=True, help_text="For billing-period data", null=True
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Plant code, meter ID, airport pair, etc.",
                        max_length=255,
                    ),
                ),
                ("vendor", models.CharField(blank=True, max_length=255)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("sap_document_number", models.CharField(blank=True, max_length=50)),
                ("sap_plant_code", models.CharField(blank=True, max_length=20)),
                ("sap_cost_center", models.CharField(blank=True, max_length=20)),
                ("utility_meter_id", models.CharField(blank=True, max_length=50)),
                ("utility_tariff", models.CharField(blank=True, max_length=100)),
                (
                    "travel_origin",
                    models.CharField(
                        blank=True, help_text="IATA code or city", max_length=10
                    ),
                ),
                ("travel_destination", models.CharField(blank=True, max_length=10)),
                ("travel_traveler_id", models.CharField(blank=True, max_length=50)),
                (
                    "travel_class",
                    models.CharField(
                        blank=True, help_text="economy/business/first", max_length=20
                    ),
                ),
                (
                    "travel_distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("flagged", "Flagged"),
                            ("approved", "Approved"),
                            ("locked", "Locked for Audit"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("flag_reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False,
                        help_text="True if any field was manually corrected",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-activity_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("flagged", "Flagged"),
                            ("approved", "Approved"),
                            ("locked", "Locked"),
                            ("edited", "Edited"),
                            ("unflagged", "Unflagged"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("before_state", models.JSONField(blank=True, null=True)),
                ("after_state", models.JSONField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="ingestion.emissionrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="IngestionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("sap", "SAP (Fuel & Procurement)"),
                            ("utility", "Utility (Electricity)"),
                            ("travel", "Corporate Travel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("original_filename", models.CharField(blank=True, max_length=512)),
                (
                    "original_file",
                    models.FileField(
                        blank=True, null=True, upload_to="raw_uploads/%Y/%m/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("row_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="accounts.organisation",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="ingestion.ingestionbatch",
            ),
        ),
        migrations.CreateModel(
            name="RawRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_index",
                    models.IntegerField(help_text="0-based row index within the file"),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        help_text="Column→value dict from the source file verbatim"
                    ),
                ),
                (
                    "parse_error",
                    models.TextField(
                        blank=True, help_text="Non-empty if this row failed to parse"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_rows",
                        to="ingestion.ingestionbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["row_index"],
                "unique_together": {("batch", "row_index")},
            },
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="raw_row",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ingestion.rawrow",
            ),
        ),
        migrations.AddIndex(
            model_name="emissionrecord",
            index=models.Index(
                fields=["organisation", "status"], name="ingestion_e_organis_e2aaec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emissionrecord",
            index=models.Index(
                fields=["organisation", "scope", "activity_date"],
                name="ingestion_e_organis_46b879_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emissionrecord",
            index=models.Index(fields=["batch"], name="ingestion_e_batch_i_e7d0fe_idx"),
        ),
    ]
